#include <LilyGoWatch.h>

#define SERIAL_BAUD_RATE 115200
#define SCREEN_BRIGHTNESS 255

#define CPU_FREQ_MIN 80
#define CPU_FREQ_MAX 240

#define SILENT_WAKE_TIME_SECONDS 30
#define SCREEN_ACTIVE_TIME 15000
#define SCREEN_ACTIVE_TIMEOUT_ENABLED false

#define SILENT_WAKE_ENABLE false
#define BT_NAME "SH TTGO WATCH"

#define POWER_CHARGE_CURRENT 500
