#define LILYGO_WATCH_2020_V1    
#define LILYGO_WATCH_LVGL     

#include <LilyGoWatch.h>

#define SERIAL_BAUD_RATE 115200
#define SCREEN_BRIGHTNESS 255

#define CPU_FREQ_MIN 80
#define CPU_FREQ_MAX 240

#define SILENT_WAKE_TIME_SECONDS 30
#define SCREEN_ACTIVE_TIME 15000

